CREATE TABLE pelicula (
  id_pelicula       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo            VARCHAR(100),
  anio              INTEGER,
  director          VARCHAR(60),
  genero            VARCHAR(60),
  sinopsis          VARCHAR(255)
);